function skillsMember() {
    // Load the skills data
    var skills = [
        { skill: 'HTML', level: 'Intermediate' },
        { skill: 'CSS', level: 'Intermediate' },
        { skill: 'JavaScript', level: 'Intermediate' },
        { skill: 'React', level: 'Intermediate' },
        { skill: 'Python', level: 'Intermediate' },
        { skill: 'Java', level: 'Intermediate' },
        { skill: 'C++', level: 'Intermediate' },
        { skill: 'C#', level: 'Intermediate' },
        { skill: 'PHP', level: 'Intermediate' },
        { skill: 'SQL', level: 'Intermediate' },
        { skill: 'Node.js', level: 'Intermediate' },
        { skill: 'MongoDB', level: 'Intermediate' },
        { skill: 'MySQL', level: 'Intermediate' },
        { skill: 'PostgreSQL', level: 'Intermediate' },
        { skill: 'Git', level: 'Intermediate' },
        { skill: 'Docker', level: 'Intermediate' },
        { skill: 'AWS', level: 'Intermediate' },
        { skill: 'Azure', level: 'Intermediate' },
        { skill: 'Google Cloud', level: 'Intermediate' },
        { skill: 'Firebase', level: 'Intermediate' },
        { skill: 'Heroku', level: 'Intermediate' },
        { skill: 'Netlify', level: 'Intermediate' },
        { skill: 'Vercel', level: 'Intermediate' },
        { skill: 'Jest', level: 'Intermediate' },
        { skill: 'Mocha', level: 'Intermediate' },
        { skill: 'Chai', level: 'Intermediate' },
        { skill: 'Karma', level: 'Intermediate' },
        { skill: 'Puppeteer', level: 'Intermediate' },
        { skill: 'Cypress', level: 'Intermediate' },
        { skill: 'Playwright', level: 'Intermediate' },
        { skill: 'Selenium', level: 'Intermediate' },
        { skill: 'Jasmine', level: 'Intermediate' },
        { skill: 'WebdriverIO', level: 'Intermediate' },
        { skill: 'Appium', level: 'Intermediate' },
        { skill: 'Xamarin', level: 'Intermediate' },
        { skill: 'React', level: 'Intermediate' }
    ];
}